disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - file_header

included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*\.swift
                    \/\/  swift-rfc-.*
                    \/\/
                    \/\/  Created by .* on .*\.
                    \/\/